### ISSUE TITLE
Command line launch

### ISSUE THREAD

**Issue by SamIsOnMC** [Nilsen84/lunar-client-qt#81]
Im trying to directly launch lunar from the command line using `java --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=natives -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/java.io=ALL-UNNAMED -Djava.library.path=natives -cp "lunar-assets-prod-1-optifine.jar;lunar-assets-prod-2-optifine.jar;lunar-assets-prod-3-optifine.jar;lunar-libs.jar;lunar-prod-optifine.jar;vpatcher-prod.jar" -javaagent:CrackedAccount.jar com.moonsworth.lunar.patcher.LunarMain --version 1.8 --accessToken 0 --assetIndex 1.8.9 --userProperties {} --gameDir lunarGameDir/ 
--launcherVersion 2.10.0,` but this happens:

Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/tree/ClassNode
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:452)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.ClassNode
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 5 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at e:\jenkins\tmp\workspace\build\src\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed

**Comment by Nilsen84** [comment]
Add the asm libraries to the classpath

**Comment by SamIsOnMC** [comment]
how would i do that?

**Comment by SamIsOnMC** [comment]
EDIT: Tried adding to the classpath; didnt work.
`C:\Users\REDACTED\Documents\susCrack>java --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=natives -Dlog4j2.formatMsgNoLookups=true --add-opens java.base/java.io=ALL-UNNAMED -Djava.library.path=natives -cp "lunar-assets-prod-1-optifine.jar;lunar-assets-prod-2-optifine.jar;lunar-assets-prod-3-optifine.jar;lunar-libs.jar;lunar-prod-optifine.jar;vpatcher-prod.jar;asm-9.2.jar;asm-tree-9.2.jar" -javaagent:CrackedAccount.jar com.moonsworth.lunar.patcher.LunarMain --version 1.8 --accessToken 0 --assetIndex 1.8.9 --userProperties {} --gameDir lunarGameDir/ --launcherVersion 2.10.0
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:503)
Caused by: java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "username" is null
        at me.onils.crackedaccount.Agent.premain(Agent.java:86)
        ... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at e:\jenkins\tmp\workspace\build\src\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed`
